// Generated by https://quicktype.io

class PopularMovieModel {
  String? backdropPath;
  int? id;
  String? originalLanguage;
  String? originalTitle;
  String? overview;
  double? popularity;
  String? posterPath;
  String? releaseDate;
  String? title;
  double? voteAverage;
  int? voteCount;

  PopularMovieModel({
    this.backdropPath,
    this.id,
    this.originalLanguage,
    this.originalTitle,
    this.overview,
    this.popularity,
    this.posterPath,
    this.releaseDate,
    this.title,
    this.voteAverage,
    this.voteCount,
  });

  factory PopularMovieModel.fromMap(Map<String, dynamic> mapa) {
    return PopularMovieModel(
        backdropPath: mapa['backdrop_path'] ?? '',
        id: mapa['id'],
        originalLanguage: mapa['original_language'],
        originalTitle: mapa['original_title'],
        overview: mapa['overview'],
        popularity: mapa['popularity'],
        posterPath: mapa['poster_path'] ?? '',
        releaseDate: mapa['release_date'],
        title: mapa['title'],
        voteAverage: mapa['vote_average'] is int
            ? (mapa['vote_average'] as int).toDouble()
            : mapa['vote_average'],
        voteCount: mapa['vote_count']);
  }
}
